//created on: 19-Apr-2015
package com.SOOHP



//list any import classes here.

///import com.SOOHP.Clue
///import com.SOOHP.ClueList
///import java.util.Vector
import java.util.Vector

//declare any global variables here


rule "ClueList is 1 & 2"
when
$C : Vector()
///$E : ClueList()
$D : Vector((this contains "Prnt.Cable.Light.Green.Steady.Yes")&&(this contains "email.offline.Yes")&&(this not contains "test1"))
then
	System.out.println("rule 1 fired");
	$C.add("test1");
end

rule "ClueList is 1"
when
$C : Vector()
$D : Vector((this contains "email.canReceive.Yes")&&(this contains "Prnt.Light.Green.Steady.Yes")&&(this not contains "test2"))
then
	System.out.println("rule 2 fired");
	$C.add("test2");
end

rule "ClueList is 2"
when
$C : Vector()
$D : Vector((this contains "Prnt.Noise.Grinding.Yes")&&(this contains "Prnt.Light.Orange.Flashing.Yes")&&(this not contains "test3"))
then
	System.out.println("rule 3 fired");
	$C.add("test3");
end
